### ISSUE TITLE
Nómina electrónica

### ISSUE THREAD

**Issue by AndreaMelendez** [miguelhuertas/eFacturacionColombia_V2.Firma#11]
Hola, si para firmar facturas se enviaba un tipo firmado 1, notas crédito (2), notas débito (3), que número se especifica para la nómina electrónica, no lo veo especificado en el repositorio

Te agradecería mucho la ayuda!

**Comment by miguelhuertas** [comment]
Hola, cada tipo de documento tiene su función _(sobrecargada)_; para nómina son **FirmarNominaIndividual** y **FirmarAjusteNominaIndividual** respectivamente.
