### ISSUE TITLE
Error al enviar los documentos firmados a la DIAN

### ISSUE THREAD

**Issue by carlosvasquez0** [miguelhuertas/eFacturacionColombia_V2.Firma#2]
Estoy obteniendo el siguiente mensaje:

> Error al parsear xml. Namespace prefix 'ds' is not defined

Al momento de enviar el documento firmado a la DIAN, con la libreria, yo reviso el documento firmado generado por la libreria y este si tiene dicha declaracion de nombre de espacio, ¿Que puede estar ocurriendo?

[b8063f5c84391abcb6beeea35837118319be83478fae9070b1c231de8bc8415f-XMLSIGNED.zip](https://github.com/miguelhuertas/eFacturacionColombia_V2.Firma/files/3522534/b8063f5c84391abcb6beeea35837118319be83478fae9070b1c231de8bc8415f-XMLSIGNED.zip)

![unnamed1](https://user-images.githubusercontent.com/16739761/63383604-ba38b280-c362-11e9-9af4-4d6478842440.png)
![unnamed2](https://user-images.githubusercontent.com/16739761/63383605-ba38b280-c362-11e9-997f-5bf5a44b21a9.png)

**Comment by miguelhuertas** [comment]
Hola @carlosvasquez0 
Ese namespace (ds) también tiene que ir definido en el nodo principal de los documentos XML.
