### ISSUE TITLE
Exception "Elemento no encontrado"

### ISSUE THREAD

**Issue by jonathanarvaez** [miguelhuertas/eFacturacionColombia_V2.Firma#4]
Al colocar una factura para firmar me genera Exception "Elemento no encontrado". navegando un poco en el código la excepción se genera en SetSignatureDestination(SignatureDocument sigDocument, SignatureXPathExpression destination) donde no se puede establecer un nodo destino para la firma. Me doy cuenta que usando SelectSingleNode y buscando la expresión "/fe:Invoice/ext:UBLExtensions/ext:UBLExtension[2]/ext:ExtensionContent" no la encuentra, veo que fe esta como:
xpathExpression.Namespaces.Add("fe", "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2") y mi factura electronica de prueba de la DIAN tiene en la cabecera : xmlns:fe="http://www.dian.gov.co/contratos/facturaelectronica/v1" entonces al cambiar lo anterior por:
xpathExpression.Namespaces.Add("fe", "http://www.dian.gov.co/contratos/facturaelectronica/v1");
el encuentra el nodo, pero no se si es un error, algo viejo o la factura que tengo de prueba es la que debe cambiar.

**Comment by miguelhuertas** [comment]
Este repositorio funciona para documentos XML de la versión 2 (Validación Previa) de la factura electrónica.
