### ISSUE TITLE
new X509Certificate2(RutaCertificado, ClaveCertificado) IIS Crash

### ISSUE THREAD

**Issue by jupagose** [miguelhuertas/eFacturacionColombia_V2.Firma#5]
Cuando trato de firmar un documento en un servidor Windows 2012R2, genera un crash en el método:

FirmaElectronica.FirmarEvento(byte[] bytesXml, DateTime fecha) 

linea 168 

 `using (parametros.Signer = new Signer(new X509Certificate2(RutaCertificado, ClaveCertificado)))`

El  problema se genera al intentar crear el nuevo certificado, la solución es cambiar el constructor de la creación del certificado es decir cambiar 

`new X509Certificate2(RutaCertificado, ClaveCertificado)`

por 

`new X509Certificate2(RutaCertificado, ClaveCertificado, X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable);`

NOTA: Curiosamente funciona bien sin ningún cambio en windows 10

**Comment by miguelhuertas** [comment]
Gracias por el dato @jupagose. Saludos
